/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface EntropySwapERC7984ToERC20Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "deposit"
      | "entropyOracle"
      | "erc20Token"
      | "exchangeRate"
      | "getEncryptedBalance"
      | "getEntropyOracle"
      | "requestSwapWithEntropy"
      | "swapRequestCount"
      | "swapRequests"
      | "swapWithEntropy"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "SwapRequested" | "Swapped"): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "erc20Token",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "exchangeRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestSwapWithEntropy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRequestCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapWithEntropy",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "erc20Token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "exchangeRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSwapWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapRequestCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapWithEntropy",
    data: BytesLike
  ): Result;
}

export namespace SwapRequestedEvent {
  export type InputTuple = [user: AddressLike, requestId: BigNumberish];
  export type OutputTuple = [user: string, requestId: bigint];
  export interface OutputObject {
    user: string;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwappedEvent {
  export type InputTuple = [
    user: AddressLike,
    encryptedAmount: BytesLike,
    erc20Amount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    encryptedAmount: string,
    erc20Amount: bigint
  ];
  export interface OutputObject {
    user: string;
    encryptedAmount: string;
    erc20Amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropySwapERC7984ToERC20 extends BaseContract {
  connect(runner?: ContractRunner | null): EntropySwapERC7984ToERC20;
  waitForDeployment(): Promise<this>;

  interface: EntropySwapERC7984ToERC20Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  erc20Token: TypedContractMethod<[], [string], "view">;

  exchangeRate: TypedContractMethod<[], [bigint], "view">;

  getEncryptedBalance: TypedContractMethod<
    [account: AddressLike],
    [string],
    "view"
  >;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  requestSwapWithEntropy: TypedContractMethod<
    [tag: BytesLike],
    [bigint],
    "payable"
  >;

  swapRequestCount: TypedContractMethod<[], [bigint], "view">;

  swapRequests: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  swapWithEntropy: TypedContractMethod<
    [
      requestId: BigNumberish,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [encryptedAmount: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "erc20Token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "exchangeRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEncryptedBalance"
  ): TypedContractMethod<[account: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestSwapWithEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "swapRequestCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "swapRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "swapWithEntropy"
  ): TypedContractMethod<
    [
      requestId: BigNumberish,
      encryptedAmount: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "SwapRequested"
  ): TypedContractEvent<
    SwapRequestedEvent.InputTuple,
    SwapRequestedEvent.OutputTuple,
    SwapRequestedEvent.OutputObject
  >;
  getEvent(
    key: "Swapped"
  ): TypedContractEvent<
    SwappedEvent.InputTuple,
    SwappedEvent.OutputTuple,
    SwappedEvent.OutputObject
  >;

  filters: {
    "SwapRequested(address,uint256)": TypedContractEvent<
      SwapRequestedEvent.InputTuple,
      SwapRequestedEvent.OutputTuple,
      SwapRequestedEvent.OutputObject
    >;
    SwapRequested: TypedContractEvent<
      SwapRequestedEvent.InputTuple,
      SwapRequestedEvent.OutputTuple,
      SwapRequestedEvent.OutputObject
    >;

    "Swapped(address,bytes,uint256)": TypedContractEvent<
      SwappedEvent.InputTuple,
      SwappedEvent.OutputTuple,
      SwappedEvent.OutputObject
    >;
    Swapped: TypedContractEvent<
      SwappedEvent.InputTuple,
      SwappedEvent.OutputTuple,
      SwappedEvent.OutputObject
    >;
  };
}
